# Generated by Django 3.1.6 on 2021-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_price', models.IntegerField()),
                ('email', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('payment_method', models.TextField()),
                ('transcetion_no', models.IntegerField()),
                ('account', models.IntegerField()),
                ('delevary_address', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
                ('delevered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(),
        ),
    ]
